"use strict";
let aluno;
aluno = ["aluno1", "aluno2", "aluno3"];
console.log(aluno);
let sujeito;
sujeito = ["aluno4", 15, "frontEnd"];
sujeito.push("aluno5", 30, "BacktEnd");
sujeito.push(49, "FullStack");
console.log(sujeito);
let statusPedido;
statusPedido = ["em produção", "saiu para entrega", "pedido entregue"];
console.log(statusPedido);
